/* Real HTTP/browser acceptance. Install Playwright in a separate tooling folder,
   run two existing app instances, and pass browser executable through env. */
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');const {chromium}=require('playwright');
const origin=process.env.UI_ORIGIN||'http://127.0.0.1:8765';
const noMapOrigin=process.env.UI_NO_MAP_ORIGIN||'http://127.0.0.1:8766';
const output=process.env.UI_OUTPUT||'/tmp/projectmind-ui-evidence';fs.mkdirSync(output,{recursive:true});
(async()=>{
 const launch={headless:true,args:['--no-sandbox']};
 if(process.env.UI_BROWSER)launch.executablePath=process.env.UI_BROWSER;
 const browser=await chromium.launch(launch);const context=await browser.newContext({viewport:{width:1440,height:960}});
 // Fonts are test-environment-only. Product uses OS fonts and has no new assets/dependencies.
 if(process.env.UI_FONT_ROOT){const fontRoot=process.env.UI_FONT_ROOT;await context.route('**/test-fonts/*',route=>route.fulfill({path:path.join(fontRoot,'files',new URL(route.request().url()).pathname.split('/').pop())}));const css=fs.readFileSync(path.join(fontRoot,'400.css'),'utf8').replaceAll('./files/','/test-fonts/');await context.addInitScript(css=>{document.addEventListener('DOMContentLoaded',()=>{const style=document.createElement('style');style.textContent=css+'\n:root,body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans SC",sans-serif!important}pre,code{font-family:Menlo,"Noto Sans SC",monospace!important}';document.head.append(style);});},css);}
 const page=await context.newPage();const errors=[];const checks=[];page.on('pageerror',e=>errors.push(e.message));
 const check=(name)=>{checks.push(name);console.log('PASS',name);};
 const screenshot=async name=>{await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(output,name+'.png')});};
 await page.goto(origin);await page.locator('#home-attention .attention-panel').first().waitFor();
 assert.equal(await page.locator('body').getAttribute('data-view'),'home');check('Overview aggregates existing APIs');await screenshot('overview');
 if(await page.locator('.ux-dialog').isVisible())await page.locator('.ux-dialog').getByRole('button',{name:'关闭',exact:true}).click(); await page.keyboard.press('Control+k');assert.equal(await page.locator('#command-dialog').evaluate(n=>n.open),true);await page.locator('#command-input').fill('仓库');await page.keyboard.press('Enter');assert.equal(await page.locator('body').getAttribute('data-view'),'explorer');check('Command palette: shortcut, search, keyboard selection');
 await page.locator('[data-view="arch"]').click();await page.locator('[data-entry="planning"]').click();await page.locator('#arch-planning-title').fill('UI acceptance · planning');await page.locator('#arch-planning-goals').fill('Browser verification only. Draft remains a labeled sample.');await page.locator('#arch-create-planning button').click();await page.locator('#arch-workspace').waitFor({state:'visible'});assert.equal(await page.locator('#arch-entry-card').isVisible(),false);check('Creation switches to the daily workspace');
 await page.locator('.ux-sample-options summary').click();await page.locator('#arch-sample-button').click();await page.getByRole('button',{name:'应用到草稿',exact:true}).waitFor();await page.getByRole('button',{name:'应用到草稿',exact:true}).click();await page.locator('#arch-map-stage .map-node').first().waitFor();assert.match(await page.locator('#arch-sample-banner').innerText(),/演示/);check('Sample provenance survives generation/application');
 await page.locator('#arch-map-stage .map-node').first().click();assert.equal(await page.locator('#arch-correction-card').evaluate(n=>n.parentElement.classList.contains('details')),true);await page.locator('#view-arch').evaluate(n=>n.scrollTop=0);await screenshot('architecture');
 await page.locator('[data-arch-tab="outline"]').click();assert.ok(await page.locator('#arch-outline .outline-row').count()>0);await page.locator('#arch-outline .outline-row').first().click();await page.locator('[data-arch-tab="canvas"]').click();check('Canvas / outline share selected node and Inspector');
 const node=page.locator('#arch-map-stage .map-node').first();const rect=await node.boundingBox();await page.mouse.move(rect.x+20,rect.y+25);await page.mouse.down();await page.mouse.move(rect.x+60,rect.y+60,{steps:8});await page.mouse.up();assert.match(await page.locator('#arch-draft-status').innerText(),/浏览器/);check('Drag saves viewing layout without architecture mutations');
 await page.locator('#canvas-zoom-in').click();assert.equal(await page.locator('#canvas-zoom').innerText(),'110%');await page.locator('#canvas-fit').click();check('Canvas zoom and fit');
 await node.dblclick();const title=page.locator('#arch-details-content input').first();await title.fill('Browser edited responsibility');await page.getByRole('button',{name:'保存职责修改',exact:true}).click();await page.locator('#arch-map-stage').getByText('Browser edited responsibility',{exact:true}).waitFor();check('Inspector edits persist through existing CAS endpoint');
 await page.locator('#toggle-inspector').click();assert.equal(await page.locator('#view-arch .details').isVisible(),false);await page.locator('#toggle-inspector').click();check('Inspector can collapse and reopen');
 await page.locator('#arch-add-node').click();const modal=page.locator('.workspace-dialog');await modal.getByLabel('名称',{exact:true}).fill('Browser modal node');await modal.getByLabel('职责说明',{exact:true}).fill('Human input candidate');await modal.getByRole('button',{name:'添加到草稿',exact:true}).click();await page.locator('#arch-map-stage').getByText('Browser modal node',{exact:true}).waitFor();check('Add node modal persists a human input candidate');
 await page.locator('#arch-add-node').click();await page.keyboard.press('Escape');await page.locator('.workspace-dialog').waitFor({state:'detached'});check('Modal cancellation does not mutate the graph');
 await page.locator('#arch-new-workspace').click();await page.getByRole('button',{name:/我有项目 · 导入已有代码/}).click();await page.locator('[data-entry="existing"]').click();await page.locator('#arch-repo-path').fill(process.env.UI_REPO||process.cwd());await page.locator('#arch-existing-title').fill('UI acceptance · pinned evidence');await page.locator('#arch-existing-desc').fill('Actual repository code evidence test.');await page.locator('#arch-create-existing button').click();await page.locator('#arch-workspace').waitFor({state:'visible'});await page.locator('.ux-sample-options summary').click();await page.locator('#arch-sample-button').click();await page.getByRole('button',{name:'应用到草稿',exact:true}).click();await page.locator('#arch-map-stage .map-node').first().click();await page.getByRole('button',{name:'查看固定版本代码 ↗',exact:true}).first().click();await page.locator('#explorer-file-path').getByText('app.py',{exact:true}).waitFor();assert.ok(await page.locator('.syntax-keyword').count()>0);check('Inspector opens declared evidence at pinned commit with safe syntax highlighting');

 await page.locator('[data-view="decisions"]').click();const decisions=page.frameLocator('#decisions-frame');await decisions.locator('#category-title').getByText('关键决策',{exact:true}).waitFor();await decisions.locator('#new').click();await decisions.locator('#edit-title').fill('UI acceptance decision');await decisions.locator('#edit-body').fill('## Context\nBrowser acceptance fixture. Human record, not approved model.');await decisions.getByRole('button',{name:'保存记录',exact:true}).click();await decisions.locator('.reader h2.title').getByText('UI acceptance decision',{exact:true}).waitFor();assert.match(await decisions.locator('#reader').innerText(),/不代表团队已批准/);check('Decision records preserve unverified status and save');await screenshot('decisions');
 await page.locator('[data-view="worklog"]').click();const logs=page.frameLocator('#worklog-frame');await logs.locator('#category-title').waitFor();await logs.locator('#file').setInputFiles({name:'ui-acceptance.md',mimeType:'text/markdown',buffer:Buffer.from('# Imported worklog\nMarkdown import via unchanged chunk API.')});await logs.locator('.reader h2.title').getByText('ui-acceptance',{exact:true}).waitFor();check('Worklog Markdown import/read');await screenshot('worklog');
 await page.locator('[data-view="collab"]').click();const handoff=page.frameLocator('#collab-frame');await handoff.locator('#generate').waitFor();await handoff.locator('#generate').click();await handoff.locator('#summary').waitFor({state:'visible'});assert.equal(await handoff.locator('#md').isEnabled(),true);check('Handoff generation and exports use unchanged backend');await screenshot('handoff');
 await page.locator('[data-view="review"]').click();await page.locator('#review-run').click();await page.locator('#review-output').waitFor({state:'visible'});await screenshot('changes');check('Changes real Git comparison / facts / proposals');
 await page.locator('[data-view="explorer"]').click();await page.locator('#explorer-repo-path').fill(process.env.UI_REPO||process.cwd());await page.locator('#explorer-open-form button').click();await page.locator('#explorer-workspace').waitFor({state:'visible'});await page.locator('#explorer-search').fill('app.py');await page.locator('#explorer-tree').getByText('app.py',{exact:true}).click();await page.locator('#explorer-file-view .explorer-body').waitFor();check('Repository tree / source viewer');await screenshot('repository');
 await page.locator('[data-view="home"]').click();await page.locator('#home-activity .activity-row').first().waitFor();check('Overview refreshes actual work records after navigation');
 await page.setViewportSize({width:390,height:844});await screenshot('mobile');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);check('Small screen: no page horizontal overflow');await page.setViewportSize({width:1440,height:960});
 // Endpoint failure must show unknown/unavailable, not zeros/old data.
 await page.route('**/api/extensions/worklog?action=list',route=>route.fulfill({status:503,contentType:'application/json',body:'{"error":"test unavailable"}'}));await page.locator('#home-sync').click();await page.locator('#home-activity').getByText('工作记录当前不可用。',{exact:true}).waitFor();check('Overview handles read failure honestly');
 const noMap=await context.newPage();noMap.on('pageerror',e=>errors.push(e.message));await noMap.goto(noMapOrigin);await noMap.locator('body[data-map-mode="false"]').waitFor();await noMap.locator('[data-view="decisions"]').click();assert.equal(await noMap.locator('#decisions-frame').getAttribute('src'),null);assert.equal(await noMap.locator('#view-decisions .mode-note').isVisible(),true);check('No-map mode prevents unsupported iframe/API composition');
 assert.deepEqual(errors,[]);check('No browser JavaScript exceptions');
 fs.writeFileSync(path.join(output,'browser-report.json'),JSON.stringify({status:'PASS',checks,errors,origin,notes:'Temporary browser fixtures; no real AI run, no human-approved model created.'},null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
